version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2021-12-20T22-07-16Z
    command: server /data0 /data1 /data2 /data3 --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - '9000:9000'
      - '9001:9001'
