version: "3"
services:
  minio:
    image: minio/minio:RELEASE.2020-11-25T22-36-25Z
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data0 /data1 /data2 /data3
